export MPI_HOME=$(dirname $(which mpirun))/..
export MPI_INCLUDE_PATH=$MPI_HOME/include
export MPI_CXX_LIBRARIES=$MPI_HOME/lib/libmpi.so
export HDF5_HOME=/public/home/zhangxin/external-libraries/hdf5/hdf5 # in snsc
export HDF5_INCLUDE_PATH=$HDF5_HOME/include
export HDF5_CXX_LIBRARIES=$HDF5_HOME/lib/libhdf5.so
export CFLAGS="-I$MPI_INCLUDE_PATH -I$HDF5_INCLUDE_PATH"
export CPPFLAGS="-I$MPI_INCLUDE_PATH -I$HDF5_INCLUDE_PATH"
export LDFLAGS="-L$MPI_CXX_LIBRARIES -lmpi -L$HDF5_CXX_LIBRARIES -lhdf5"
export HDF5_MPI="ON"
python -m pip install --no-cache-dir --no-binary=h5py h5py  > .log.txt 2>&1 & code .log.txt
