export MPI_DIR=$(dirname $(which mpirun))/..
export MPI_INCLUDE_PATH=$MPI_DIR/include
export MPI_CXX_LIBRARIES=$MPI_DIR/lib/libmpi.so
export HDF5_DIR=/public/home/zhangxin/external-libraries/hdf5/hdf5 # in snsc
export HDF5_INCLUDE_PATH=$HDF5_DIR/include
export HDF5_CXX_LIBRARIES=$HDF5_DIR/lib/libhdf5.so
export LD_LIBRARY_PATH=$MPI_CXX_LIBRARIES:$HDF5_CXX_LIBRARIES:$LD_LIBRARY_PATH
export CFLAGS="-I$MPI_INCLUDE_PATH -I$HDF5_INCLUDE_PATH"
export LDFLAGS="-L$MPI_CXX_LIBRARIES -L$HDF5_CXX_LIBRARIES$LDFLAGS"
export HDF5_MPI="ON"
# python -m pip install --no-cache-dir --no-binary=h5py h5py  > .log.txt 2>&1 & code .log.txt
python -m pip install --no-binary=h5py h5py
