import ctypes
from qcu import Pointer
def testWilsonDslashQcu(fermion_out:Pointer, fermion_in:Pointer,
              gauge:Pointer, params: ctypes.c_void_p, argv: ctypes.c_void_p) -> None: ...
def applyWilsonDslashQcu(fermion_out:Pointer, fermion_in:Pointer, gauge:Pointer,
                  params: ctypes.c_void_p, argv: ctypes.c_void_p) -> None: ...
def testCloverDslashQcu(fermion_out:Pointer, fermion_in:Pointer,
                    gauge:Pointer, params: ctypes.c_void_p, argv: ctypes.c_void_p) -> None: ...
def applyCloverDslashQcu(fermion_out:Pointer, fermion_in:Pointer, gauge:Pointer,
                  params: ctypes.c_void_p, argv: ctypes.c_void_p) -> None: ...
def applyBistabCgQcu(fermion_out:Pointer, fermion_in:Pointer, gauge:Pointer,
                    params: ctypes.c_void_p, argv: ctypes.c_void_p) -> None: ...
def applyCgQcu(fermion_out:Pointer, fermion_in:Pointer, gauge:Pointer,
                    params: ctypes.c_void_p, argv: ctypes.c_void_p) -> None: ...
def applyGmresIrQcu(fermion_out:Pointer, fermion_in:Pointer, gauge:Pointer,
                    params: ctypes.c_void_p, argv: ctypes.c_void_p) -> None: ...